// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.614.0
// Original source is Copyright © Microsoft. Licensed under the MIT license
using System;
#pragma warning disable CS1589, CS0419, CA1416, CS0618
namespace Silk.NET.DirectX;

/// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS"]/*'/>
[Flags]
public enum D3D12VideoEncoderAv1PictureControlFlags
{
    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_NONE"]/*'/>

    None = 0,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_ERROR_RESILIENT_MODE"]/*'/>

    EnableErrorResilientMode = 0x1,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_DISABLE_CDF_UPDATE"]/*'/>

    DisableCdfUpdate = 0x2,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_PALETTE_ENCODING"]/*'/>

    EnablePaletteEncoding = 0x4,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_SKIP_MODE"]/*'/>

    EnableSkipMode = 0x8,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_FRAME_REFERENCE_MOTION_VECTORS"]/*'/>

    FrameReferenceMotionVectors = 0x10,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_FORCE_INTEGER_MOTION_VECTORS"]/*'/>

    ForceIntegerMotionVectors = 0x20,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ALLOW_INTRA_BLOCK_COPY"]/*'/>

    AllowIntraBlockCopy = 0x40,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_USE_SUPER_RESOLUTION"]/*'/>

    UseSuperResolution = 0x80,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_DISABLE_FRAME_END_UPDATE_CDF"]/*'/>

    DisableFrameEndUpdateCdf = 0x100,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_FRAME_SEGMENTATION_AUTO"]/*'/>

    EnableFrameSegmentationAuto = 0x200,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_FRAME_SEGMENTATION_CUSTOM"]/*'/>

    EnableFrameSegmentationCustom = 0x400,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ENABLE_WARPED_MOTION"]/*'/>

    EnableWarpedMotion = 0x800,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_REDUCED_TX_SET"]/*'/>

    ReducedTxSet = 0x1000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_MOTION_MODE_SWITCHABLE"]/*'/>

    MotionModeSwitchable = 0x2000,

    /// <include file='D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAG_ALLOW_HIGH_PRECISION_MV"]/*'/>

    AllowHighPrecisionMv = 0x4000,
}
