// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.614.0
// Original source is Copyright © Microsoft. Licensed under the MIT license
using System.Runtime.Versioning;
#pragma warning disable CS1589, CS0419, CA1416, CS0618
namespace Silk.NET.DirectX;

/// <include file='D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.xml' path='doc/member[@name="D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE"]/*'/>
[SupportedOSPlatform("windows10.0.19041.0")]
public enum D3D12VideoExtensionCommandParameterType
{
    /// <include file='D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.xml' path='doc/member[@name="D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE_UINT8"]/*'/>

    Uint8 = 0,

    /// <include file='D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.xml' path='doc/member[@name="D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE_UINT16"]/*'/>

    Uint16 = 1,

    /// <include file='D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.xml' path='doc/member[@name="D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE_UINT32"]/*'/>

    Uint32 = 2,

    /// <include file='D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.xml' path='doc/member[@name="D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE_UINT64"]/*'/>

    Uint64 = 3,

    /// <include file='D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.xml' path='doc/member[@name="D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE_SINT8"]/*'/>

    Sint8 = 4,

    /// <include file='D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.xml' path='doc/member[@name="D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE_SINT16"]/*'/>

    Sint16 = 5,

    /// <include file='D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.xml' path='doc/member[@name="D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE_SINT32"]/*'/>

    Sint32 = 6,

    /// <include file='D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.xml' path='doc/member[@name="D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE_SINT64"]/*'/>

    Sint64 = 7,

    /// <include file='D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.xml' path='doc/member[@name="D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE_FLOAT"]/*'/>

    Float = 8,

    /// <include file='D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.xml' path='doc/member[@name="D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE_DOUBLE"]/*'/>

    Double = 9,

    /// <include file='D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.xml' path='doc/member[@name="D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE.D3D12_VIDEO_EXTENSION_COMMAND_PARAMETER_TYPE_RESOURCE"]/*'/>

    Resource = 10,
}
