// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from d3d12video.h in microsoft/DirectX-Headers tag v1.614.0
// Original source is Copyright © Microsoft. Licensed under the MIT license
#pragma warning disable CS1589, CS0419, CA1416, CS0618
namespace Silk.NET.DirectX;

/// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS"]/*'/>
public enum D3D12VideoEncoderCodecConfigurationHevcFlags
{
    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_NONE"]/*'/>

    None = 0,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_DISABLE_LOOP_FILTER_ACROSS_SLICES"]/*'/>

    DisableLoopFilterAcrossSlices = 0x1,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_ALLOW_REQUEST_INTRA_CONSTRAINED_SLICES"]/*'/>

    AllowRequestIntraConstrainedSlices = 0x2,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_ENABLE_SAO_FILTER"]/*'/>

    EnableSaoFilter = 0x4,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_ENABLE_LONG_TERM_REFERENCES"]/*'/>

    EnableLongTermReferences = 0x8,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_USE_ASYMETRIC_MOTION_PARTITION"]/*'/>

    UseAsymetricMotionPartition = 0x10,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_ENABLE_TRANSFORM_SKIPPING"]/*'/>

    EnableTransformSkipping = 0x20,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_USE_CONSTRAINED_INTRAPREDICTION"]/*'/>

    UseConstrainedIntraprediction = 0x40,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_TRANSFORM_SKIP_ROTATION"]/*'/>

    TransformSkipRotation = 0x80,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_TRANSFORM_SKIP_CONTEXT"]/*'/>

    TransformSkipContext = 0x100,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_IMPLICIT_RDPCM"]/*'/>

    ImplicitRdpcm = 0x200,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_EXPLICIT_RDPCM"]/*'/>

    ExplicitRdpcm = 0x400,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_EXTENDED_PRECISION_PROCESSING"]/*'/>

    ExtendedPrecisionProcessing = 0x800,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_INTRA_SMOOTHING_DISABLED"]/*'/>

    IntraSmoothingDisabled = 0x1000,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_HIGH_PRECISION_OFFSETS"]/*'/>

    HighPrecisionOffsets = 0x2000,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_PERSISTENT_RICE_ADAPTATION"]/*'/>

    PersistentRiceAdaptation = 0x4000,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_CABAC_BYPASS_ALIGNMENT"]/*'/>

    CabacBypassAlignment = 0x8000,

    /// <include file='D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.xml' path='doc/member[@name="D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAGS.D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC_FLAG_SEPARATE_COLOUR_PLANE"]/*'/>

    SeparateColourPlane = 0x10000,
}
