// Copyright © Tanner Gooding and Contributors. Licensed under the MIT License (MIT). See License.md in the repository root for more information.
// Ported from d3d12.h in microsoft/DirectX-Headers tag v1.614.0
// Original source is Copyright © Microsoft. Licensed under the MIT license
using System;
#pragma warning disable CS1589, CS0419, CA1416, CS0618
namespace Silk.NET.DirectX;

/// <include file='D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS.xml' path='doc/member[@name="D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS"]/*'/>
[Flags]
public enum D3D12RaytracingAccelerationStructureBuildFlags
{
    /// <include file='D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS.xml' path='doc/member[@name="D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS.D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_NONE"]/*'/>

    None = 0,

    /// <include file='D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS.xml' path='doc/member[@name="D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS.D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_ALLOW_UPDATE"]/*'/>

    AllowUpdate = 0x1,

    /// <include file='D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS.xml' path='doc/member[@name="D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS.D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_ALLOW_COMPACTION"]/*'/>

    AllowCompaction = 0x2,

    /// <include file='D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS.xml' path='doc/member[@name="D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS.D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_PREFER_FAST_TRACE"]/*'/>

    PreferFastTrace = 0x4,

    /// <include file='D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS.xml' path='doc/member[@name="D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS.D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_PREFER_FAST_BUILD"]/*'/>

    PreferFastBuild = 0x8,

    /// <include file='D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS.xml' path='doc/member[@name="D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS.D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_MINIMIZE_MEMORY"]/*'/>

    MinimizeMemory = 0x10,

    /// <include file='D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS.xml' path='doc/member[@name="D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAGS.D3D12_RAYTRACING_ACCELERATION_STRUCTURE_BUILD_FLAG_PERFORM_UPDATE"]/*'/>

    PerformUpdate = 0x20,
}
